### ISSUE TITLE
Ampliar el número de caracteres para la construcción de la sal

### ISSUE THREAD

**Issue by rafonsecad** [lvtsum/virtc-system#1]
Actualmente se tiene estos caracteres para la construir la sal

https://github.com/lvtsum/virtc-system/blob/daf09921053171d2866f4c2385225f28dcb92ef3/src/lib/salt.ts#L24

Lo cual es muy limitado teniendo en cuenta que se pueden incluir todos los caracteres ascii o unicode si se manejan como números, o como parte del Uint8Array, también se podría usar la función estándar [btoa ](https://developer.mozilla.org/en-US/docs/Web/API/btoa)para codificar a base64

**Comment by lvtsum** [comment]
¡Hola! Tomé en cuenta tu opinión en este [commit](https://github.com/lvtsum/virtc-system/commit/aeafb1f48cd6b167db6bc1f7d54f843254100da7).

- Agregué más caracteres unicode, con el tiempo iré agregando más y más. (Claro está que no es posible/necesario incluir TODOS los caracteres unicode)
- Sigo manejando este string de caracteres unicode como UTF8.
- Utilizo SHA3 en reemplazo de base64. Esto es porque necesitaba una longitud fija.

¡Gracias por tu aporte!
